services:
  php:
    image: php:7.4-cli
    volumes:
      - ./www:/var/www/html
      - ./src:/var/www/src
      - ./templates:/var/www/templates
    ports:
      - "8080:8080"  
    command: php -S 0.0.0.0:8080 -t /var/www/html