services:
  php:
    image: php:7.4-cli
    volumes:
      - ./www:/var/www/html
      - ./src:/var/www/src
      - ./templates:/var/www/templates
    ports:
      - "8080:8080"  
    command: >
      bash -c "docker-php-ext-install pdo pdo_mysql &&
                php -S 0.0.0.0:8080 -t /var/www/html"
  mysql: 
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=my_project
      - MYSQL_USER=qwe
      - MYSQL_PASSWORD=qwe
      - MYSQL_ROOT_PASSWORD=qwe
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1 